### ISSUE TITLE
MVP GUI Scaffold

### ISSUE THREAD

**Issue by Semuca** [Semuca/road-safety-scanner#5]
## Description
The basic GUI must be set up according to design. The idea of this issue is that it covers the basic scaffolding so that the GUI for each module can be ticketed up and built separately.

The library used should be wxWidgets- not tkInter, which has numerous compatibility problems due to age. The boilerplate should already be set up in the root, however the GUI scaffold core should be set up in it's own module. This means the GUI for each module can be contained in that module.

## Prerequisites
The GUI design must be completed.

**Comment by xull3** [comment]
**Home Page** - This is the initial screen that user will see when the application is opened. The search feature is primarily there for the user to use the filter feature (located on the right of the search bar) to set the filters they need to apply on the journals. Some or all fields can be set as "required" so if the user forgets to set filters and upload the journals, then it will prompt them with a user friendly error to hint them to set filters.

![Home Page](https://github.com/user-attachments/assets/fabfc6b9-7466-4fd5-a1cf-c3ce00597420)


____________________________________________________________________________________________________________________________________


**Filter Page** - This is the initial design of the filter page. Will need to be edited as per the clients requirements. We need to add ALL filtering options they client wants.

![Filter Interface](https://github.com/user-attachments/assets/298e47ed-a56c-4363-bed8-b180259bed76)


____________________________________________________________________________________________________________________________________

**Journal Upload Page** - The page below shows what the user will see upon selecting the "Upload" tab on the top right of the Home Page.

![Upload Interface](https://github.com/user-attachments/assets/b7378ffb-9e0b-47a1-a4f3-372c4929044b)

Then, as the user populates the page with journals, it will start displaying the uploaded journals on the page.

![UploadList Interface](https://github.com/user-attachments/assets/b91aa245-3615-425d-b525-f16bb005f230)


____________________________________________________________________________________________________________________________________

**Results Page** - This page will display the processed journals/the final results from LLMs.

![Results Interface](https://github.com/user-attachments/assets/8646bed6-1bd4-4fef-8bf6-9741b8b35265)

**Comment by Semuca** [comment]
Swapped over to using Qt widgets through PySide6 over wxwidgets
